# Site settings
title: 月球猫的鱼塘
description: "hhahahahhaa"
url: "http://yqm.io"
author:
  name: ""
  email: ""
  url: ""

# Build settings
#baseurl: /blog # Change this to your relative path (ex: /blog/), or leave just a /
#markdown: kramdown
#source: .
#destination: ./_site
#permalink: /:title
paginate: 2
# paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

# 友情链接
friends:
  - title: "月球猫博客"
    url: "http://yqm.io"
  - title: "Qubot"
    url: "http://qubot.cn"
  - title: "炫Q香蕉派"
    url: "http://mikuq.com"
  - title: "XiaoLu Lab"
    url: "https://0w0.pw"
  - title: "井底添蛙DIY"
    url: "http://www.smilefrog.net"
  - title: "Neuron Black"
    url: "http://neuronblack.cc"
  - title: "狗爬社区"
    url: "http://forum.godpub.com/forum.php"
  - title: "NyaMoe – いつ空"
    url: "https://www.nyamoe.com"
  - title: "小窝"
    url: "http://www.300er.com"
  - title: "天宇小站"
    url: "http://makt.top"
  - title: "Water的个人空间"
    url: "http://wp-cloud.cc"
